### ISSUE TITLE
cannot get screen size on init

### ISSUE THREAD

**Issue by marklai1998** [eloytoro/react-screen-size#3]
I'm making a responsive layout that has mobile exclusive classes
But I cannot tell if the screen is sm or not when the page first load,
I have to resize through the breakpoint so it will trigger it

so is it possible to get the screen size when it init??

I like the way that your library syntax is similar to redux
so I hope I can stick to this library

**Comment by eloytoro** [comment]
Right now youre given the option to set the initial parameters of the screen size by passing the `screenSize` prop to the provider, this should solve your issue.

However it would be very nice to have this calculated automatically at pageload, ill consider adding this as default behavior
